version: "3"
services:
    pihole:
        container_name: pihole
        networks:
            lannet:
                ipv4_address: 192.168.0.6
        environment:
            - TZ=America/Detroit
            - VIRTUAL_HOST=pi.hole
            - PROXY_LOCATION=pi.hole
            - FTLCONF_LOCAL_IPV4=127.0.0.1
            - WEBPASSWORD=CHANGE_THIS_VALUE
        volumes:
            - ./etc-pihole:/etc/pihole
            - ./etc-dnsmasq.d:/etc/dnsmasq.d
        dns:
            - 127.0.0.1
            - 208.67.222.222
            - 208.67.220.220
        restart: unless-stopped
        hostname: pi.hole
        image: pihole/pihole:latest
        cap_add:
            - NET_ADMIN
    nginxproxymanager:
        container_name: npm
        networks:
            lannet:
                ipv4_address: 192.168.0.7
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        restart: unless-stopped
        image: jc21/nginx-proxy-manager:latest
networks:
    lannet:
        external: true
        name: lannet


